---
title: "snotelr"
author: "Tao"
date: "1/7/2022"
output: html_document
---

```{r}
#install.packages("snotelr")
library("snotelr")
library("ggplot2")
library("foreign")
#install.packages("cropgrowdays")
library("cropgrowdays")
library("dplyr")
```

```{r}
snotel_explorer()
```

# Bogus Basin	978
```{r}
max_swe_df<-data.frame(id=123456, year="1234",max_swe=123456789)
max_swe_df

id=978
 Sys.time()
  df <- snotel_download(site_id = id , internal = TRUE)
  df$date<-as.POSIXct( df$date,format="%Y-%m-%d")
  df$year<-format( df$date, "%Y")
  max_swe<-df %>%
    group_by(year) %>%
    summarize(max_swe=max(snow_water_equivalent))
  max_swe$id<-id
  max_swe_df<-rbind(max_swe_df,max_swe)
  head(df)
  Sys.time()
```

```{r}
west_mnt_snotel<-read.dbf("C:/Users/taohuang/Documents/Tao/Data/norwest/west_mnt_snotel.dbf")
west_mnt_snotel$GAGE_ID<-as.character(west_mnt_snotel$GAGE_ID)
load("C:/Users/taohuang/Downloads/IDWQ_PAHydroML-main/meanAugT_idmt_df.Rdata")

west_mnt_snotel_id<-unique(west_mnt_snotel[west_mnt_snotel$GAGE_ID %in% meanAugT_df$site_no ,]$SNOTEL_ID)
west_mnt_snotel_id<-west_mnt_snotel_id[west_mnt_snotel_id>0]
```


```{r}
max_swe_df<-data.frame(id=123456, year="1234",max_swe=123456789)
max_swe_df
for (id in west_mnt_snotel_id) {
  Sys.time()
  df <- snotel_download(site_id = id , internal = TRUE)
  df$date<-as.POSIXct( df$date,format="%Y-%m-%d")
  df$year<-format( df$date, "%Y")
  max_swe<-df %>%
    group_by(year) %>%
    summarize(max_swe=max(snow_water_equivalent))
    max_swe$id<-id
  max_swe_df<-rbind(max_swe_df,max_swe)
  head(df)
  Sys.time()
}

save(max_swe_df,file="max_swe_df.Rdata")
```

```{r}
plot(df$date ,df$snow_water_equivalent )
summary(df$snow_water_equivalent)
plot(df[df$date>= as.POSIXct( "2022-04-09",format="%Y-%m-%d" ) ,]$date, df[df$date>= as.POSIXct( "2022-04-09",format="%Y-%m-%d" ) ,]$snow_water_equivalent)

```

```{r}
b<-read.csv("Bogus_Basin.csv")
b$date<-as.POSIXct(b$date, format="%m/%d/%Y")
colnames(b)<-c(colnames(b)[1:23],"Year 2022",colnames(b)[25:30], "Median ('91-'20)",colnames(b)[32:34])
head(b)
```

```{r}
plot(b$doy ,b$`Year 2022` , xlab = "day of water year")
par(new=T)
plot(b$doy ,b$`Median ('91-'20)`  , xlab = "day of water year")
```

```{r}
ggplot( b, aes(doy)) + 
  geom_line(aes(y =  `Year 2022` ), color="Red" )+
  geom_line(aes(y =    `Median ('91-'20)`  ))+ ylab("Snow Water Equivalent (in.)")+xlab("Day of Water Year")
```


```{r}
ggplot(  ) + 
  geom_line(data=b,aes(x= doy, y =  `Year 2022` ,colour="2022")  )+
  geom_line(data=b,aes(x= doy, y =    `Median ('91-'20)`  ,colour="Median ('91-'20)"))+ ylab("Snow Water Equivalent (in.)")+xlab("Day of Water Year")+
  scale_color_manual(name = " ", values = c("2022" = "Red", "Median ('91-'20)" = "Blue"))+ggtitle( "Bogus Basin SNOTEL")
```

